# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from traqapi.models.o_auth2_client import OAuth2Client
from traqapi.models.o_auth2_client_detail import OAuth2ClientDetail
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GETCLIENT200RESPONSE_ONE_OF_SCHEMAS = ["OAuth2Client", "OAuth2ClientDetail"]

class GetClient200Response(BaseModel):
    """
    GetClient200Response
    """
    # data type: OAuth2Client
    oneof_schema_1_validator: Optional[OAuth2Client] = None
    # data type: OAuth2ClientDetail
    oneof_schema_2_validator: Optional[OAuth2ClientDetail] = None
    actual_instance: Optional[Union[OAuth2Client, OAuth2ClientDetail]] = None
    one_of_schemas: Set[str] = { "OAuth2Client", "OAuth2ClientDetail" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = GetClient200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: OAuth2Client
        if not isinstance(v, OAuth2Client):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OAuth2Client`")
        else:
            match += 1
        # validate data type: OAuth2ClientDetail
        if not isinstance(v, OAuth2ClientDetail):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OAuth2ClientDetail`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GetClient200Response with oneOf schemas: OAuth2Client, OAuth2ClientDetail. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GetClient200Response with oneOf schemas: OAuth2Client, OAuth2ClientDetail. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into OAuth2Client
        try:
            instance.actual_instance = OAuth2Client.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OAuth2ClientDetail
        try:
            instance.actual_instance = OAuth2ClientDetail.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GetClient200Response with oneOf schemas: OAuth2Client, OAuth2ClientDetail. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GetClient200Response with oneOf schemas: OAuth2Client, OAuth2ClientDetail. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], OAuth2Client, OAuth2ClientDetail]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


