# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictInt, StrictStr

class MessageStamp(BaseModel):
    """
    メッセージに押されたスタンプ  # noqa: E501
    """
    user_id: StrictStr = Field(..., alias="userId", description="ユーザーUUID")
    stamp_id: StrictStr = Field(..., alias="stampId", description="スタンプUUID")
    count: StrictInt = Field(..., description="スタンプ数")
    created_at: datetime = Field(..., alias="createdAt", description="スタンプが最初に押された日時")
    updated_at: datetime = Field(..., alias="updatedAt", description="スタンプが最後に押された日時")
    __properties = ["userId", "stampId", "count", "createdAt", "updatedAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MessageStamp:
        """Create an instance of MessageStamp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MessageStamp:
        """Create an instance of MessageStamp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MessageStamp.parse_obj(obj)

        _obj = MessageStamp.parse_obj({
            "user_id": obj.get("userId"),
            "stamp_id": obj.get("stampId"),
            "count": obj.get("count"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt")
        })
        return _obj


