# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime as _datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from traqapi.models.message_stamp import MessageStamp
from typing import Optional, Set
from typing_extensions import Self

class Message(BaseModel):
    """
    メッセージ
    """ # noqa: E501
    id: StrictStr = Field(description="メッセージUUID")
    user_id: StrictStr = Field(description="投稿者UUID", alias="userId")
    channel_id: StrictStr = Field(description="チャンネルUUID", alias="channelId")
    content: StrictStr = Field(description="メッセージ本文")
    created_at: _datetime = Field(description="投稿日時", alias="createdAt")
    updated_at: _datetime = Field(description="編集日時", alias="updatedAt")
    pinned: StrictBool = Field(description="ピン留めされているかどうか")
    stamps: List[MessageStamp] = Field(description="押されているスタンプの配列")
    thread_id: Optional[StrictStr] = Field(description="スレッドUUID", alias="threadId")
    __properties: ClassVar[List[str]] = ["id", "userId", "channelId", "content", "createdAt", "updatedAt", "pinned", "stamps", "threadId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Message from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in stamps (list)
        _items = []
        if self.stamps:
            for _item in self.stamps:
                if _item:
                    _items.append(_item.to_dict())
            _dict['stamps'] = _items
        # set to None if thread_id (nullable) is None
        # and model_fields_set contains the field
        if self.thread_id is None and "thread_id" in self.model_fields_set:
            _dict['threadId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Message from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "userId": obj.get("userId"),
            "channelId": obj.get("channelId"),
            "content": obj.get("content"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "pinned": obj.get("pinned"),
            "stamps": [MessageStamp.from_dict(_item) for _item in obj["stamps"]] if obj.get("stamps") is not None else None,
            "threadId": obj.get("threadId")
        })
        return _obj


