# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from traqapi.models.message_stamp import MessageStamp

class Message(BaseModel):
    """
    メッセージ  # noqa: E501
    """
    id: StrictStr = Field(..., description="メッセージUUID")
    user_id: StrictStr = Field(..., alias="userId", description="投稿者UUID")
    channel_id: StrictStr = Field(..., alias="channelId", description="チャンネルUUID")
    content: StrictStr = Field(..., description="メッセージ本文")
    created_at: datetime = Field(..., alias="createdAt", description="投稿日時")
    updated_at: datetime = Field(..., alias="updatedAt", description="編集日時")
    pinned: StrictBool = Field(..., description="ピン留めされているかどうか")
    stamps: conlist(MessageStamp) = Field(..., description="押されているスタンプの配列")
    thread_id: Optional[StrictStr] = Field(..., alias="threadId", description="スレッドUUID")
    __properties = ["id", "userId", "channelId", "content", "createdAt", "updatedAt", "pinned", "stamps", "threadId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Message:
        """Create an instance of Message from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in stamps (list)
        _items = []
        if self.stamps:
            for _item in self.stamps:
                if _item:
                    _items.append(_item.to_dict())
            _dict['stamps'] = _items
        # set to None if thread_id (nullable) is None
        # and __fields_set__ contains the field
        if self.thread_id is None and "thread_id" in self.__fields_set__:
            _dict['threadId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Message:
        """Create an instance of Message from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Message.parse_obj(obj)

        _obj = Message.parse_obj({
            "id": obj.get("id"),
            "user_id": obj.get("userId"),
            "channel_id": obj.get("channelId"),
            "content": obj.get("content"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt"),
            "pinned": obj.get("pinned"),
            "stamps": [MessageStamp.from_dict(_item) for _item in obj.get("stamps")] if obj.get("stamps") is not None else None,
            "thread_id": obj.get("threadId")
        })
        return _obj


