# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OAuth2ResponseType(str, Enum):
    """
    OAuth2ResponseType
    """

    """
    allowed enum values
    """
    CODE = 'code'
    TOKEN = 'token'
    NONE = 'none'

    @classmethod
    def from_json(cls, json_str: str) -> OAuth2ResponseType:
        """Create an instance of OAuth2ResponseType from a JSON string"""
        return OAuth2ResponseType(json.loads(json_str))


