# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OAuth2ResponseType(str, Enum):
    """
    OAuth2ResponseType
    """

    """
    allowed enum values
    """
    CODE = 'code'
    TOKEN = 'token'
    NONE = 'none'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OAuth2ResponseType from a JSON string"""
        return cls(json.loads(json_str))


