# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr

class PatchClientRequest(BaseModel):
    """
    OAuth2クライアント情報変更リクエスト  # noqa: E501
    """
    name: Optional[constr(strict=True, max_length=32, min_length=1)] = Field(None, description="クライアント名")
    description: Optional[constr(strict=True, max_length=1000)] = Field(None, description="説明")
    callback_url: Optional[StrictStr] = Field(None, alias="callbackUrl", description="コールバックURL")
    developer_id: Optional[StrictStr] = Field(None, alias="developerId", description="クライアント開発者UUID")
    __properties = ["name", "description", "callbackUrl", "developerId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PatchClientRequest:
        """Create an instance of PatchClientRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PatchClientRequest:
        """Create an instance of PatchClientRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PatchClientRequest.parse_obj(obj)

        _obj = PatchClientRequest.parse_obj({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "callback_url": obj.get("callbackUrl"),
            "developer_id": obj.get("developerId")
        })
        return _obj


