# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from traqapi.models.bot_mode import BotMode
from typing import Optional, Set
from typing_extensions import Self

class PatchBotRequest(BaseModel):
    """
    BOT情報変更リクエスト
    """ # noqa: E501
    display_name: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, description="BOTユーザー表示名", alias="displayName")
    description: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = Field(default=None, description="BOTの説明")
    privileged: Optional[StrictBool] = Field(default=None, description="特権")
    mode: Optional[BotMode] = None
    endpoint: Optional[StrictStr] = Field(default=None, description="BOTサーバーエンドポイント")
    developer_id: Optional[StrictStr] = Field(default=None, description="移譲先の開発者UUID", alias="developerId")
    subscribe_events: Optional[List[StrictStr]] = Field(default=None, description="購読するイベント", alias="subscribeEvents")
    __properties: ClassVar[List[str]] = ["displayName", "description", "privileged", "mode", "endpoint", "developerId", "subscribeEvents"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchBotRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchBotRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "displayName": obj.get("displayName"),
            "description": obj.get("description"),
            "privileged": obj.get("privileged"),
            "mode": obj.get("mode"),
            "endpoint": obj.get("endpoint"),
            "developerId": obj.get("developerId"),
            "subscribeEvents": obj.get("subscribeEvents")
        })
        return _obj


