# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist

class PatchChannelSubscribersRequest(BaseModel):
    """
    チャンネル購読者編集リクエスト  # noqa: E501
    """
    on: Optional[conlist(StrictStr)] = Field(None, description="通知をオンにするユーザーのUUID配列")
    off: Optional[conlist(StrictStr)] = Field(None, description="通知をオフにするユーザーのUUID配列")
    __properties = ["on", "off"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PatchChannelSubscribersRequest:
        """Create an instance of PatchChannelSubscribersRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PatchChannelSubscribersRequest:
        """Create an instance of PatchChannelSubscribersRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PatchChannelSubscribersRequest.parse_obj(obj)

        _obj = PatchChannelSubscribersRequest.parse_obj({
            "on": obj.get("on"),
            "off": obj.get("off")
        })
        return _obj


