# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist, constr
from traqapi.models.o_auth2_scope import OAuth2Scope

class PostClientRequest(BaseModel):
    """
    OAuth2クライアント作成リクエスト  # noqa: E501
    """
    name: constr(strict=True, max_length=32, min_length=1) = Field(..., description="クライアント名")
    callback_url: StrictStr = Field(..., alias="callbackUrl", description="コールバックURL")
    scopes: conlist(OAuth2Scope) = Field(..., description="要求スコープの配列")
    description: constr(strict=True, max_length=1000) = Field(..., description="説明")
    __properties = ["name", "callbackUrl", "scopes", "description"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostClientRequest:
        """Create an instance of PostClientRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostClientRequest:
        """Create an instance of PostClientRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostClientRequest.parse_obj(obj)

        _obj = PostClientRequest.parse_obj({
            "name": obj.get("name"),
            "callback_url": obj.get("callbackUrl"),
            "scopes": obj.get("scopes"),
            "description": obj.get("description")
        })
        return _obj


