# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from traqapi.models.bot_mode import BotMode
from typing import Optional, Set
from typing_extensions import Self

class PostBotRequest(BaseModel):
    """
    BOT作成リクエスト
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=16)] = Field(description="BOTユーザーID 自動的に接頭辞\"BOT_\"が付与されます")
    display_name: Annotated[str, Field(strict=True, max_length=32)] = Field(description="BOTユーザー表示名", alias="displayName")
    description: Annotated[str, Field(strict=True, max_length=1000)] = Field(description="BOTの説明")
    mode: BotMode
    endpoint: Optional[StrictStr] = Field(default=None, description="BOTサーバーエンドポイント BOT動作モードがHTTPの場合必須です")
    __properties: ClassVar[List[str]] = ["name", "displayName", "description", "mode", "endpoint"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9_-]{1,16}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_-]{1,16}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostBotRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostBotRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "displayName": obj.get("displayName"),
            "description": obj.get("description"),
            "mode": obj.get("mode"),
            "endpoint": obj.get("endpoint")
        })
        return _obj


