# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, constr

class PostMessageRequest(BaseModel):
    """
    メッセージ投稿リクエスト  # noqa: E501
    """
    content: constr(strict=True, max_length=10000, min_length=1) = Field(..., description="メッセージ本文")
    embed: Optional[StrictBool] = Field(False, description="メンション・チャンネルリンクを自動埋め込みするか")
    __properties = ["content", "embed"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostMessageRequest:
        """Create an instance of PostMessageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostMessageRequest:
        """Create an instance of PostMessageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostMessageRequest.parse_obj(obj)

        _obj = PostMessageRequest.parse_obj({
            "content": obj.get("content"),
            "embed": obj.get("embed") if obj.get("embed") is not None else False
        })
        return _obj


