# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictBool, StrictStr, constr, validator

class StampWithThumbnail(BaseModel):
    """
    スタンプ情報とサムネイルの有無  # noqa: E501
    """
    id: StrictStr = Field(..., description="スタンプUUID")
    name: constr(strict=True) = Field(..., description="スタンプ名")
    creator_id: StrictStr = Field(..., alias="creatorId", description="作成者UUID")
    created_at: datetime = Field(..., alias="createdAt", description="作成日時")
    updated_at: datetime = Field(..., alias="updatedAt", description="更新日時")
    file_id: StrictStr = Field(..., alias="fileId", description="ファイルUUID")
    is_unicode: StrictBool = Field(..., alias="isUnicode", description="Unicode絵文字か")
    has_thumbnail: StrictBool = Field(..., alias="hasThumbnail", description="サムネイルの有無")
    __properties = ["id", "name", "creatorId", "createdAt", "updatedAt", "fileId", "isUnicode", "hasThumbnail"]

    @validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9_-]{1,32}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_-]{1,32}$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StampWithThumbnail:
        """Create an instance of StampWithThumbnail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StampWithThumbnail:
        """Create an instance of StampWithThumbnail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StampWithThumbnail.parse_obj(obj)

        _obj = StampWithThumbnail.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "creator_id": obj.get("creatorId"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt"),
            "file_id": obj.get("fileId"),
            "is_unicode": obj.get("isUnicode"),
            "has_thumbnail": obj.get("hasThumbnail")
        })
        return _obj


