# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class TopicChangedEvent(BaseModel):
    """
    トピック変更イベント  # noqa: E501
    """
    user_id: StrictStr = Field(..., alias="userId", description="変更者UUID")
    before: StrictStr = Field(..., description="変更前トピック")
    after: StrictStr = Field(..., description="変更後トピック")
    __properties = ["userId", "before", "after"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TopicChangedEvent:
        """Create an instance of TopicChangedEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TopicChangedEvent:
        """Create an instance of TopicChangedEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TopicChangedEvent.parse_obj(obj)

        _obj = TopicChangedEvent.parse_obj({
            "user_id": obj.get("userId"),
            "before": obj.get("before"),
            "after": obj.get("after")
        })
        return _obj


