# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime as _datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class Webhook(BaseModel):
    """
    Webhook情報
    """ # noqa: E501
    id: StrictStr = Field(description="WebhookUUID")
    bot_user_id: StrictStr = Field(description="WebhookユーザーUUID", alias="botUserId")
    display_name: StrictStr = Field(description="Webhookユーザー表示名", alias="displayName")
    description: StrictStr = Field(description="説明")
    secure: StrictBool = Field(description="セキュアWebhookかどうか")
    channel_id: StrictStr = Field(description="デフォルトの投稿先チャンネルUUID", alias="channelId")
    owner_id: StrictStr = Field(description="オーナーUUID", alias="ownerId")
    created_at: _datetime = Field(description="作成日時", alias="createdAt")
    updated_at: _datetime = Field(description="更新日時", alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "botUserId", "displayName", "description", "secure", "channelId", "ownerId", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Webhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Webhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "botUserId": obj.get("botUserId"),
            "displayName": obj.get("displayName"),
            "description": obj.get("description"),
            "secure": obj.get("secure"),
            "channelId": obj.get("channelId"),
            "ownerId": obj.get("ownerId"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


