# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictBool, StrictStr

class Webhook(BaseModel):
    """
    Webhook情報  # noqa: E501
    """
    id: StrictStr = Field(..., description="WebhookUUID")
    bot_user_id: StrictStr = Field(..., alias="botUserId", description="WebhookユーザーUUID")
    display_name: StrictStr = Field(..., alias="displayName", description="Webhookユーザー表示名")
    description: StrictStr = Field(..., description="説明")
    secure: StrictBool = Field(..., description="セキュアWebhookかどうか")
    channel_id: StrictStr = Field(..., alias="channelId", description="デフォルトの投稿先チャンネルUUID")
    owner_id: StrictStr = Field(..., alias="ownerId", description="オーナーUUID")
    created_at: datetime = Field(..., alias="createdAt", description="作成日時")
    updated_at: datetime = Field(..., alias="updatedAt", description="更新日時")
    __properties = ["id", "botUserId", "displayName", "description", "secure", "channelId", "ownerId", "createdAt", "updatedAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Webhook:
        """Create an instance of Webhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Webhook:
        """Create an instance of Webhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Webhook.parse_obj(obj)

        _obj = Webhook.parse_obj({
            "id": obj.get("id"),
            "bot_user_id": obj.get("botUserId"),
            "display_name": obj.get("displayName"),
            "description": obj.get("description"),
            "secure": obj.get("secure"),
            "channel_id": obj.get("channelId"),
            "owner_id": obj.get("ownerId"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt")
        })
        return _obj


