---
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/users/me":
    get:
      summary: Get User
      operationId: get_user_users_me_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
      security:
      - traO: []
  "/users/groups":
    get:
      summary: Get User Groups
      operationId: get_user_groups_users_groups_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  "$ref": "#/components/schemas/GroupDetails"
                type: array
                title: Response Get User Groups Users Groups Get
      security:
      - traO: []
  "/groups/{group_id}":
    get:
      summary: Get Group
      operationId: get_group_groups__group_id__get
      parameters:
      - required: true
        schema:
          type: string
          title: Group Id
        name: group_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GroupDetails"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
  "/groups/{group_id}/tasks":
    get:
      summary: Get Group Tasks
      operationId: get_group_tasks_groups__group_id__tasks_get
      parameters:
      - required: true
        schema:
          type: string
          title: Group Id
        name: group_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  "$ref": "#/components/schemas/TaskDetails"
                type: array
                title: Response Get Group Tasks Groups  Group Id  Tasks Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
  "/tasks":
    post:
      summary: Create Task
      operationId: create_task_tasks_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateTaskReqDTO"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TaskDetails"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
  "/tasks/{task_id}":
    delete:
      summary: Delete Task
      operationId: delete_task_tasks__task_id__delete
      parameters:
      - required: true
        schema:
          type: string
          title: Task Id
        name: task_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
    patch:
      summary: Edit Task
      operationId: edit_task_tasks__task_id__patch
      parameters:
      - required: true
        schema:
          type: string
          title: Task Id
        name: task_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateTaskReqDTO"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TaskDetails"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
  "/labels":
    post:
      summary: Create Label
      operationId: create_label_labels_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LabelCreate"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Label"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
  "/labels/{label_id}":
    delete:
      summary: Delete Label
      operationId: delete_label_labels__label_id__delete
      parameters:
      - required: true
        schema:
          type: string
          title: Label Id
        name: label_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
    patch:
      summary: Edit Label
      operationId: edit_label_labels__label_id__patch
      parameters:
      - required: true
        schema:
          type: string
          title: Label Id
        name: label_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LabelUpdate"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Label"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
      security:
      - traO: []
components:
  schemas:
    CreateTaskReqDTO:
      properties:
        title:
          type: string
          title: Title
        content:
          type: string
          title: Content
        message_id:
          type: string
          title: Message Id
        due_date:
          type: string
          title: Due Date
        group_id:
          type: string
          title: Group Id
        assigned_user_ids:
          items:
            type: string
          type: array
          title: Assigned User Ids
      type: object
      required:
      - title
      - content
      - group_id
      - assigned_user_ids
      title: CreateTaskReqDTO
    GroupDetails:
      properties:
        id:
          type: string
          title: Id
        remind_channel_id:
          type: string
          title: Remind Channel Id
        periodic_remind_at:
          type: string
          title: Periodic Remind At
        created_at:
          type: string
          title: Created At
        updated_at:
          type: string
          title: Updated At
        user_ids:
          items:
            type: string
          type: array
          title: User Ids
      type: object
      required:
      - id
      - remind_channel_id
      - periodic_remind_at
      - created_at
      - updated_at
      - user_ids
      title: GroupDetails
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Label:
      properties:
        name:
          type: string
          title: Name
        id:
          type: string
          title: Id
        group_id:
          type: string
          title: Group Id
        created_at:
          type: string
          title: Created At
        updated_at:
          type: string
          title: Updated At
      type: object
      required:
      - name
      - id
      - group_id
      - created_at
      - updated_at
      title: Label
    LabelCreate:
      properties:
        name:
          type: string
          title: Name
        group_id:
          type: string
          title: Group Id
      type: object
      required:
      - name
      - group_id
      title: LabelCreate
    LabelUpdate:
      properties:
        name:
          type: string
          title: Name
      type: object
      required:
      - name
      title: LabelUpdate
    TaskDetails:
      properties:
        title:
          type: string
          title: Title
        content:
          type: string
          title: Content
        message_id:
          type: string
          title: Message Id
        due_date:
          type: string
          title: Due Date
        id:
          type: string
          title: Id
        group_id:
          type: string
          title: Group Id
        created_at:
          type: string
          title: Created At
        updated_at:
          type: string
          title: Updated At
        assigned_user_ids:
          items:
            type: string
          type: array
          title: Assigned User Ids
      type: object
      required:
      - title
      - content
      - id
      - group_id
      - created_at
      - updated_at
      - assigned_user_ids
      title: TaskDetails
    UpdateTaskReqDTO:
      properties:
        title:
          type: string
          title: Title
        content:
          type: string
          title: Content
        message_id:
          type: string
          title: Message Id
        due_date:
          type: string
          title: Due Date
        assigned_user_ids:
          items:
            type: string
          type: array
          title: Assigned User Ids
      type: object
      required:
      - title
      - content
      - assigned_user_ids
      title: UpdateTaskReqDTO
    User:
      properties:
        id:
          type: string
          title: Id
        remind_channel_id:
          type: string
          title: Remind Channel Id
        periodic_remind_at:
          type: string
          title: Periodic Remind At
        created_at:
          type: string
          title: Created At
        updated_at:
          type: string
          title: Updated At
      type: object
      required:
      - id
      - remind_channel_id
      - periodic_remind_at
      - created_at
      - updated_at
      title: User
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    traO:
      type: apiKey
      in: header
      name: X-Forwarded-User

